name: test

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install PySDM==1.25
      - uses: matlab-actions/setup-matlab@v0
        with:
          release: R2021a
      - uses: matlab-actions/run-command@v0
        with:
          command: test
